### ISSUE TITLE
[Feature request] Colour palet for background

### ISSUE THREAD

**Issue by JMulder99** [redwarp/gif-wallpaper#106]
Although the current background colours are well picked, it would be nice to choose from a colour palet. That way, I can match the background colour with the rest of my setup.

**Comment by redwarp** [comment]
It's a good idea, I need to find a nice and easy library to pick a color, something with a simple and good design.

**Comment by russellbanks** [comment]
> It's a good idea, I need to find a nice and easy library to pick a color, something with a simple and good design.

I can recommend [Sheets](https://github.com/maxkeppeler/sheets) which provides a modern looking [colour picker module](https://github.com/maxkeppeler/sheets#color).

<img src="https://raw.githubusercontent.com/maxkeppeler/sheets/main/art/ColorSheet%20Dialog%20Templates.png" height="162"><img src="https://raw.githubusercontent.com/maxkeppeler/sheets/main/art/ColorSheet%20Dialog%20Custom.png" height="162">

As an alternative, [Material Dialogs ](https://github.com/afollestad/material-dialogs) is another good library that provides a [colour picker module](https://github.com/afollestad/material-dialogs#color).
<img src="https://raw.githubusercontent.com/afollestad/material-dialogs/main/art/color_chooser.png" height="250">

**Comment by redwarp** [comment]
Currently rewriting the whole app with Jetpack compose, for the heck of it, so the priority of it has lowered somewhat, sorry.
