### ISSUE TITLE
I'd like to help with a translation to spanish!

### ISSUE THREAD

**Issue by Preyesianyeha** [redwarp/gif-wallpaper#113]
I'm new to github but i want to help with a translation, so if you're interested, reply, i think #

**Comment by redwarp** [comment]
That would be so cool!!!
I use POEditor to handle the translations: https://poeditor.com/join/project?hash=QaDkuFZTp2
You can join there and help, I just created the Spanish language.
Let me know if it woks! Then I'll have to setup a few things, and translations can be easily synchronised between POEditor and GitHub

**Comment by Preyesianyeha** [comment]
I have joined to the spanish translation, but now that i have the project in my dashboard, it doesn't let me access to the project, i can't click on it, idk if it's intentional, but i'll wait for a reply!

**Comment by redwarp** [comment]
Apparently I have to approve you! I just did! Let me know if it works!

**Comment by Preyesianyeha** [comment]
I have translated all texts, but idk if u are able to see them, so please tell me what can i do now.

**Comment by redwarp** [comment]
Everything is there. I should have time tomorrow to create an update with the Spanish language included, I'll keep you posted!

**Comment by Preyesianyeha** [comment]
Cool!, take your time, i'll wait :D

**Comment by redwarp** [comment]
Shall I use the name "preyesianyeha" in the readme for acknowledgement? Or do you have another nickname you prefer?

**Comment by Preyesianyeha** [comment]
If you u can use "YesIanYeha" that'd be great, preyesianyeha is some sort of placeholder for the actual nickname, but i'm lazy to change it.

**Comment by redwarp** [comment]
@Preyesianyeha so, if you are a beta tester, the update with Spanish language is released! You can join the beta testing program from the google play store ;-)

**Comment by redwarp** [comment]
@Preyesianyeha sorry to bother you again, I added a few strings to the app to add a "power saving mode". Could you log back in https://poeditor.com/projects/view?id=362629 to help me complete them?

**Comment by Preyesianyeha** [comment]
Sure, i'll do it!

**Comment by Preyesianyeha** [comment]
Done!
