### ISSUE TITLE
Different image between lock screen and launcher

### ISSUE THREAD

**Issue by bellegarde-c** [redwarp/gif-wallpaper#115]
Should be awesome to have a different image between lock screen and launcher.

I want a static image on my launcher and an animated one on my lockscreen.

**Comment by redwarp** [comment]
Hey @bellegarde-c 
I'm not against the idea in theory, but it's out of my hands: when you choose a live wallpaper on your device, it replaces the other wallpapers. And as far as I know, there is no way to specify though code that you want the app to only be activated on the lock screen, or launcher.
Each phone has different policy there.
So I won't be able to support that, sorry.

**Comment by wtquin** [comment]
sorry for the necro, just wanted to chime in since this would be a cool idea: could we check for device state (lock screen vs home screen, maybe check if the device is locked) and swap out the gif ourselves accordingly? i suppose this isn't super simle to implement, but it could be possible ^^

**Comment by redwarp** [comment]
Seems to be technically possible, by doing something like this: https://developer.android.com/reference/android/app/KeyguardManager#isDeviceLocked()

But that is the easy part I guess. I mean the whole app is made to have one entry, to save one file and one file only. So there will be a bit more work to change that 🤔 

Seems doable, just I make no promises (lately, I'm less keen on working on side projects during the week-end)
