### ISSUE TITLE
Feature Request: Suspend wallpaper on battery saver

### ISSUE THREAD

**Issue by ryan77627** [redwarp/gif-wallpaper#117]
I don't know if this is possible, but if it is I'd like to make a suggestion. If the battery saver mode on the phone turns on, the app should suspend gif playback to save as much power as it can. Maybe show the first frame to be simple or allow the user to choose a frame to display, but that seems like it would be complicated.

Just a thought I had while setting up my wallpaper, thanks for making this app! =D

**Comment by redwarp** [comment]
That is a nice idea! I should be able to monitor it using [ACTION_POWER_SAVE_MODE_CHANGED](https://developer.android.com/reference/android/os/PowerManager#ACTION_POWER_SAVE_MODE_CHANGED)

https://stackoverflow.com/questions/48932479/ways-to-test-power-save-mode-changed-action-power-save-mode-changed-receiver

**Comment by redwarp** [comment]
It might also be a good idea to stop the playback if the device is under THERMAL_STATUS_SEVERE or higher (api 29+)

**Comment by redwarp** [comment]
@ryan77627 alright, I'm adding a setting, that will show up for android devices with android 23+ (so marshmallow and more)

**Comment by redwarp** [comment]
@ryan77627 available now on the beta track. Rolling out to production.

**Comment by ryan77627** [comment]
Awesome, thank you so much! I just received the update (through F-Droid) and it works perfectly!
