### ISSUE TITLE
[Feature request] chose a different gif for the home and lock screen

### ISSUE THREAD

**Issue by Tachyreas** [redwarp/gif-wallpaper#128]
Hi, would it be possible to add a way to chose different gifs for the home and lockscreen ? It seems like we can only chose for the home screen or the home screen and lockscreen together.

Thanks for your work on the app, it is great ! And if there's a technical limitation making it impossible sorry for the bother. #127

**Comment by Tachyreas** [comment]
Really sorry i just saw you addressed that in another issue

**Comment by redwarp** [comment]
@Tachyreas no worries! Though to be honest I might be wrong! Maybe it is possible? I have not been able to figure it out though.
