### ISSUE TITLE
Double Tap to stop the gif

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [redwarp/gif-wallpaper#131]
It would be nice to have this feature when your battery was low or when you suddenly decided "hey, i wanna be good owner on me phone and ill stop this gif wallpaper so me phone cpu will not have to much vork".

**Comment by redwarp** [comment]
@PLAYERUNKNOWNHatsune01 there is now a setting in the app that will automatically pause the gif if you are working in battery economy mode! Open the app, click the 3 dots, click on settings. I think this should do the trick ;-)
