### ISSUE TITLE
Multiple GIF?

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [redwarp/gif-wallpaper#152]
I kinda wonder if you guys modify this already cool GIF Live Wallpaper to add some feature where it can add multiple gif in just one scene like this GIF wallpaper does "https://play.google.com/store/apps/details?id=com.awesome.giflivewallpaper" It would be nice if we can have that! :)

**Comment by redwarp** [comment]
What they do is cool but I am not sure myself how to do it in an efficient manner that does not destroy battery life, to be honest. So I decided not to, and keep the app simple.
