### ISSUE TITLE
[Feature request] Allow selection of picture from third party apps

### ISSUE THREAD

**Issue by yul-oh895** [redwarp/gif-wallpaper#171]
Hello. I have been using your app for some time and it is awesome, thank you.

My request here is to show third party apps on the gif selection page as I can search and filter gif pictures easily from there rather than the default list.

Currently if I tap on "Open Gif" it will show me only these options:
![Gif App current](https://user-images.githubusercontent.com/64549167/139209175-43837a37-2e83-4e5b-877a-ac31efd18696.png)

But with other apps that open this same screen, i can select my gallery app for example:
![Gif selextion other apps](https://user-images.githubusercontent.com/64549167/139209270-fee52382-28f1-4097-baec-b1a45a6eb0e0.png)

**Comment by redwarp** [comment]
@yul-oh895 I think I got it!

**Comment by redwarp** [comment]
Fixed!

**Comment by redwarp** [comment]
I created a new release, it will take a few days to hit google play store, and even more few days to hit f-droid.

**Comment by yul-oh895** [comment]
Thank you for the quick fix @redwarp. Looking forward to the update!

**Comment by yul-oh895** [comment]
I received the update and I can confirm this is now working.

Thanks once again @redwarp !
