### ISSUE TITLE
Apng support

### ISSUE THREAD

**Issue by maverick74** [redwarp/gif-wallpaper#172]
Hi,
I've read bug #165 but I still think apng would not add much more complexity and would be an easy implementation...

Beside, having amazing wallpapers with great colors would be awesome!!!

**Comment by redwarp** [comment]
Sorry but my stance has not really change on that topic. It would be cool, but I'm not in love with the apng lib I found, and so I decided it's out of scope for me.

**Comment by maverick74** [comment]
Ok. No problem. Just asking in case you changed your mind, because 8 bit gif (even with all the tricks we know of) is a bit limited

**Comment by redwarp** [comment]
Yeah I understand, but if you are aware of a apng library written in pure kotlin, let me know ;-)
