### ISSUE TITLE
Does your project not support implementation?

### ISSUE THREAD

**Issue by offsong** [redwarp/gif-wallpaper#173]
I want to make a k-pop artist gif wallpaper app. Your gif wallpaper seems to be the best in terms of resizing and speed. I want to use your app as a library, but don't want to support it? I have implemented gifwallaperservice, but your project is much faster and provides smoother gifs so I really want to use your project.

**Comment by redwarp** [comment]
Hey! That's a cool project you have!

Ah you have seen, Gif wallpaper is open source, under the Apache 2 license, so feel free to fork it and reuse code that you like.

And keep me posted, I'm curious about what you will create!

**Comment by offsong** [comment]
thank you! But I'm a beginner, so I don't think I can modify it and use it! It would be great if it was made into a library and used as a module, but I'm so sorry!

**Comment by redwarp** [comment]
Ah I see. Well, then sorry, I can't help you with this, as it would take a lot of time.

I would recommend that you get in development if it's dear to you, or that you find a developer that is also fan of this k-pop artist to help you.

Good luck.
