### ISSUE TITLE
[Feature Request] Set lock screen only

### ISSUE THREAD

**Issue by Kruimeldief** [redwarp/gif-wallpaper#210]
Could you add an option for setting an animated gif for the lock screen only? Currently, it shows only 2 options: home screen, and home & lock screen.

When I opt for the latter (home & lock) to set my lock screen and set another image for my home screen only, the lock screen is set to a default Samsung wallpaper.

And as a side note, it's difficult to find where I can change this setting. It seems that only when your currently wallpaper is not a gif, you get the setting of which screen you want to set with an animated gif. So often I can't change between the aformentioned options of the setting.

**Comment by redwarp** [comment]
It's not technically possible, as it's a Live Wallpaper.
It's really not an option I control, it's really build it android. For fixed (I mean by that, image wallpaper), this is not a problem. For a live wallpaper, there is nothing I can do there.

**Comment by redwarp** [comment]
And it's not possible to change once the wallpaper is set: to change between home screen only, or both, you need to re-apply the live wallpaper again (so, switching to another one, then back to this one). It's annoying, but once again, out of my hands.

**Comment by Namyar2011** [comment]
Hey, I don't know how all of this works but can it be possible to display an image on top of the home screen gif wallpaper and pause it ?

**Comment by redwarp** [comment]
I'm not sure I understand what you want to accomplish exactly to be honest?

**Comment by redwarp** [comment]
Oh I see. Well, I do not intend to do so personally.
For starter, it's not possible to choose a different gif between home and lock screen. I'm not sure how to do it, I'm not sure how to design a UI for it.

**Comment by Namyar2011** [comment]
Ok. Don't feel forced to do it. Setting a gif on the lock screen wallpaper is enough for me. Thanks for your responses.

**Comment by ghost** [comment]
@uT27SB8Ju LIt's easy to bypass. set both home and lock screen and then change home scren via built in app for wallpaper.

**Comment by uT27SB8Ju** [comment]
@Lolol4572 Unfortunately, it doesn't work. At least on my phone...
