### ISSUE TITLE
[Bug] Rare glitching of gif

### ISSUE THREAD

**Issue by russellbanks** [redwarp/gif-wallpaper#213]
I downloaded this app a few days ago and it was perfectly fine. After some time, I had severe glitching of the gif and I don't know why. At the time, I was testing the reading mode on my phone (which either dampens the screen's colours or makes them grayscale) but I don't see how this could have caused it.

To fix it, I went into the gif wallpaper app, removed the gif, and then re-added it, and I haven't had a problem since nor have I been able to reproduce it. I thought I would document this nontheless to see if there was anything that could be fixed/changed as a result of it. I took a screen recording of it when I noticed it was happening, as below.

https://user-images.githubusercontent.com/74878137/162586476-8c2b75cf-a93b-4344-83e0-f2d35d2ffa06.mp4

**Comment by redwarp** [comment]
You are not the first one to witness this! A friend of mine had that as well. It produces fascinating results but for sure it sucks :-D

But I have not been able to consistently reproduce it, so I have no clue how to fix it for now.

**Comment by redwarp** [comment]
I'm still not sure how to reproduce, closing this
