### ISSUE TITLE
Android 12 Material You global color

### ISSUE THREAD

**Issue by rustzz** [redwarp/gif-wallpaper#229]
Background color cannot set global color for system on Android 12.

For the system palette, the application color (brown) is selected, which we see when we first configure the application.  I expected that the color will be taken from the palette that I chose in the application.

Fix please

**Comment by redwarp** [comment]
Hey there. I'm not sure that I understand the issue properly here.
Could you add some more details, it maybe a screenshot of what you see, and what you expect?

**Comment by rustzz** [comment]
[Video](https://www.veed.io/view/7ee4962f-d57e-4faf-9d37-05c60325056c?sharingWidget=true)

**Comment by rustzz** [comment]
did I describe the problem well?

**Comment by redwarp** [comment]
Hey sorry for the late replay!
So as far as I know, there is no way for the live wallpaper itself to tell the system what color to use. Even though I inform the android system which are the dominant colors of the wallpapers (https://github.com/redwarp/gif-wallpaper/blob/main/app/src/main/java/net/redwarp/gifwallpaper/GifWallpaperService.kt#L126), it's simply ignored.

BUT! You can still have Android find out about the material colors by yourself. If you longpress on your background, you have the option to click on "Wallpaper & Style", then you will access to a set of colors that the Pixel launcher (I assume you are on a pixel?) computes for you, based on the current state of the wallpaper. I find it a bit infuriating, that it's not possible to set that programmatically, but that is the best I can tell you.

**Comment by redwarp** [comment]
![Screenshot_20220531-181112.png](https://user-images.githubusercontent.com/1741661/171220986-c41df7f9-1028-43b6-88bc-a781edd081a7.png)
![Screenshot_20220531-181050.png](https://user-images.githubusercontent.com/1741661/171221026-66235a5b-d74f-4af1-bb46-70428bf20cf2.png)

**Comment by rustzz** [comment]
i have android 12 (custom ROM). not pixel device
 i dont have that function for select color scheme.

but I understand that if there is a problem, then you will solve it, there would be an opportunity.  so thanks for the answers and for developing this application 
![Screenshot_20220602-135104_Обои и стиль.png](https://user-images.githubusercontent.com/74064444/171593406-2b5e6294-f019-435a-8299-3656ce814c3a.png)
