### ISSUE TITLE
Not working in when app is removed from background 

### ISSUE THREAD

**Issue by ghanimkhan** [redwarp/gif-wallpaper#237]

**Comment by redwarp** [comment]
Hey there, I'm going to need a bit more details than that ;-)

**Comment by ghanimkhan** [comment]
when the app is removed from the cash, the gif gets stuck on the lock and home screen

**Comment by redwarp** [comment]
What's kind of phone do you have, what is your Android version, can you perhaps share a video of what you see?

**Comment by ghanimkhan** [comment]
https://user-images.githubusercontent.com/30781223/173313086-56dc04e0-5e04-4cb8-be74-a69022695279.mp4

Android version 12

**Comment by ghanimkhan** [comment]
i think is the issue with the MIUI , It is working with android 12 but not on devices having MIUI

**Comment by redwarp** [comment]
Ah damn, my phone doesn't have miui, so I can't test it. I'll check to see if there is an emulator online with miui then!

**Comment by ghostnear** [comment]
Can confirm the same is happening on my MIUI device. Disabling the MIUI optimization did not help.

**Comment by ghanimkhan** [comment]
Earlier it was there but with latest  version it's not there.

https://xiaomi.eu/community/threads/miui-13-no-options-to-desactivate-miui-optimization.65050/

**Comment by redwarp** [comment]
Apparently, it's a common problem with MIUI, have you tried following the recommandations from https://dontkillmyapp.com/xiaomi ?
