### ISSUE TITLE
Color picker doesn't work 

### ISSUE THREAD

**Issue by goodrench** [redwarp/gif-wallpaper#249]
On android 12(lineage os 19) the color picker in this app doesn't work. Material you theme (based on wallpaper color) turns to brown based on the color of this app. In my early use of this app I could choose black as a color but I don't know if it stopped working with the latest update or not but no colors are available now.

**Comment by redwarp** [comment]
Hum, I don't understand exactly what you mean. Can you share screenshots of what you see?

**Comment by goodrench** [comment]
![Screenshot_20220724-044256_GIF Live Wallpaper~2.png](https://user-images.githubusercontent.com/17114531/180643126-82818892-0276-41d2-baab-224d063cbaf6.png)

If I click here to change the color... 

![Screenshot_20220724-044238_GIF Live Wallpaper~2.png](https://user-images.githubusercontent.com/17114531/180643139-f1bcc354-f9bc-4ce9-bdff-6dc6280f6753.png)

It takes me here to the color picker. 

Unfortunately clicking on the color picker only closes the option and returns the to the previous screen.

**Comment by redwarp** [comment]
Ah! I see. Well, the way the color picker works is by extracting primary colors from the first frame of the gif. Here, the only color it finds for your gif is... black. Yep, black is the primary color it seems.
So it's totally behaving as expected.
Try with a different gif, colorful, and you will see that there is more options.

**Comment by goodrench** [comment]
But the problem is that I can't select the black. And my accent colors are brownish like the background of this app's opening screen.
![Screenshot_20220724-131953_Clock.png](https://user-images.githubusercontent.com/17114531/180658832-a3d1ba36-2263-48a6-a57e-e6703de2e270.png)

![Screenshot_20220724-131909_Settings.png](https://user-images.githubusercontent.com/17114531/180658835-5ee31497-40ae-41a9-bb56-06de4dfa72ad.png)

**Comment by redwarp** [comment]
Aaaah! I see. We are not talking about the same stuff. The accent colours, it's not up to me, your phone calculate it on its own.

I'm actually not super happy about it, but...
The app declares to the system the main wallpaper colours (https://github.com/redwarp/gif-wallpaper/blob/51394cea5e5110f1a91536c8e768f979b256e953/app/src/main/java/net/redwarp/gifwallpaper/GifWallpaperService.kt#L120) but as far as I know, Android completely ignore those and decide on it's own colours for material me.

Unless there is yet another API that I don't know about, there is really nothing I can do there.

**Comment by goodrench** [comment]
So far I'm not a fan of the new theming. It looks to me like the color the theme is referring to is the color of the background in the initial screen of this app instead of the actual gif that I chose. Given a choice between using this app or switching back to my boring static wallpaper, I will continue to use this app. Very cool app and it works very well. Thanks for your work and thanks for your replies.

**Comment by redwarp** [comment]
I agree with you the "material me" as they call it is far from perfect!

Cheers, and I'm glad you enjoy the app 😉

**Comment by KrisadaFantasy** [comment]
> Aaaah! I see. We are not talking about the same stuff. The accent colours, it's not up to me, your phone calculate it on its own.
> 
> I'm actually not super happy about it, but... The app declares to the system the main wallpaper colours (
> 
> https://github.com/redwarp/gif-wallpaper/blob/51394cea5e5110f1a91536c8e768f979b256e953/app/src/main/java/net/redwarp/gifwallpaper/GifWallpaperService.kt#L120
> 
> ) but as far as I know, Android completely ignore those and decide on it's own colours for material me.
> Unless there is yet another API that I don't know about, there is really nothing I can do there.

Sorry for dig up old and closed issue! I just upgrade my phone that come with material you and face the brown problem. it's MIUI so there's no option to choose colour as I suppose there is in pixel. So I search around MIUI community on how to change accent colour and found this app: [LWP+ - customized Monet colors](https://play.google.com/store/apps/details?id=com.lb.lwp_plus) it can

- choose GIF as wallpaper
- let the system pick the colour from that wallpaper, or
- manually pick primary, secondary, and tertiary colour

Is it possible to implement something like that in GIF wallpaper as well?

**Comment by redwarp** [comment]
In terms of code, I'm doing something quite similar to LWP+. It's just that, instead of allowing the user to pick the primary, secondary etc colors, I'm extracting them from the gif. And then the system does whatever. So I'm really not sure how I could do it better to be honest.

**Comment by KrisadaFantasy** [comment]
I think GIF wallpaper works fine when it come to extract colour from the fig or have us user choose one. In this area it is indeed the same as LWP+. The difference is LWP+ managed to tell the system to use that colour as material you accent colour, while in GIF wallpaper system ignore our chosen colour and pick the brown one from activate page.

Maybe the app can change that brown page to the extracted wallpaper colour so system pick that up? This is actually what I planned to ask you before I found that LWP+ can use colour from gif.

**Comment by redwarp** [comment]
That is actually not the case.
![Screenshot_20230218-162152.png](https://user-images.githubusercontent.com/1741661/219873805-e8b1baac-a015-4c88-9eeb-c2bf22ad5c63.png)

![Screenshot_20230218-161924.png](https://user-images.githubusercontent.com/1741661/219873804-40605d78-52b5-475e-8829-fe6d644da279.png)

Using this app, you can see how the colour changed depending on the wallpaper.

There might still be a bug somewhere, I'm not saying it's perfect, but I feel that it works for the most part.

**Comment by KrisadaFantasy** [comment]
I might doing something wrong but i's not working for me. This is my screen with colour set to brown even if it should be blue.

![Screenshot_2023-02-19-09-05-13-033_com miui home](https://user-images.githubusercontent.com/85682504/219908385-087f3513-4d28-46ca-9f40-e70d08e945b6.jpg)

Brown is not is palette available to pick in change colour menu. But to be sure I choose another gif with no chance of brown.

First I disable GIF wallpaper and set static wallpaper that change accent colour to blue, then I try smaller gif and set background colour white. As seen from [Set wallpaper] button.

![Screenshot_2023-02-19-09-07-20-830_com android wallpaper livepicker](https://user-images.githubusercontent.com/85682504/219908428-fb124204-76a4-475a-ae75-7da6b0ed1af1.jpg)

It turn back to the brown.

![Screenshot_2023-02-19-09-07-35-697_com miui home](https://user-images.githubusercontent.com/85682504/219908448-df2468bf-08b7-49df-b4c6-88d56b166d72.jpg)

**Comment by redwarp** [comment]
By curiosity, what happens if you try a totally different gif? I'm wondering if there, somehow, the brown of the plants could be extracted as the secondary colour and that would be what your phone then uses?

Could you also send the GIFs so I can try to reproduce ?

**Comment by KrisadaFantasy** [comment]
I switch to this GIF that avoid all brown/orange colour. To make sure this is what GIF wallpaper pick up - all blue and grey.
![Screenshot_2023-02-20-07-36-40-308_net redwarp gifwallpaper](https://user-images.githubusercontent.com/85682504/219985936-5a101a8d-de29-4858-9858-acb32bc22732.jpg)

This is what system pick as accent colour;
![Screenshot_2023-02-20-07-36-58-566_com miui home](https://user-images.githubusercontent.com/85682504/219986036-4f4f48e3-ba87-438b-aa51-7c7960818605.jpg)

And this is GIF file, thank you!
![df9ro42-0562d4ec-618f-45e0-851e-6a6fa8477208](https://user-images.githubusercontent.com/85682504/219986071-e63a580a-d430-4167-8298-b80af4439a2d.gif)

**Comment by goodrench** [comment]
I am still suspicious of the background color of this app causing the brown issue. When this app is opened for the very first time there is the app logo against a brown background. I still have the issue on my phone after a reboot. After giving it some time, the accent colors do seem to get corrected without any interaction from me. Maybe @redwarp  could try changing the background of the app for testing purposes and see what happens? Just a thought.

**Comment by redwarp** [comment]
I have to take the time to check it, I could be indeed that the first colour send are wrong.

I probably will have some time next week 😉
