### ISSUE TITLE
'Pick a color' bottom sheet circles should have 1.dp border

### ISSUE THREAD

**Issue by russellbanks** [redwarp/gif-wallpaper#254]
The circles on the 'pick a color' bottom sheet should have a 1.dp white outline/border, to make the colours more distinguishable from the background.

![507b0b84-9952-47cb-81de-d339bf04c4e1](https://user-images.githubusercontent.com/74878137/183265305-e16906f0-a365-4f19-8c5f-ac778ead29f7.jpg)

**Comment by redwarp** [comment]
Hum, not a big fan of a border in every situation, but I could kind of detect the difference between the color and the background color, and if it's too small, add a border.
