### ISSUE TITLE
[question / clarification ] personnal data transmission

### ISSUE THREAD

**Issue by gbdomubpkm** [redwarp/gif-wallpaper#263]
Hello.
Your application is great / superbly simple to install Gif wallpapers and thank you for your nice work.
However, being particularly picky about NOT transmitting personal data, prying logs to you or third-party entities, what if your app is installed from Github or F-droid ?
I can understand that logs are transmitted in case of crashes (and only) to understand and solve the problems, but only with the consent of the user, which can be done by a switch.
Can you clarify please.
Thank you in advance.
Sincerely.

**Comment by redwarp** [comment]
Hey!

So I'm not using any framework to log anything, not even crashes. 
As far as I know, none of the libraries I use log anything.
So, whether the app is installed through fdroid or Google play, it makes no difference: it's the same code, and I don't log anything.
The only reason I have a privacy policy in the app is because Google required me to have one for some "family and kid friendly" program I don't remember enrolling in.

Still, I believe that on an Android device with the Google play services installed, some crash logs are automatically reported to Google (I can see some in the developer console). AFAIK, it's the OS doing it, not the app itself. (An app that crashed prints it's stack trace to the logs, and a system app can read and gather these logs)

**Comment by gbdomubpkm** [comment]
Thank you for your quick reply.

In fact, that's it: I had the curiosity to read your 'privacy policy', and that's what made me a little questioned and slightly 'frightened', speaking of a transmission of really indiscreet logs , while indeed,  I understood that you personally do not record/use logs.

Also in my mind I thought it makes a difference to install your app by F-droid (or Github) so out of google play store and their privacy policy, and furthermore the app is featured in F-droid like not using (without) the google play service.

That said, I don't use Android, but a degoogled OS.

**Comment by redwarp** [comment]
In the Google play console, when looking at the crashes, I can filter crash of the apps "not installed through the play store", so I assume that they collect all, and that's probably also in Google's policy!

But if you are using a degoogled os, you should be fine I hope 🤔

As of the versions of the app: the version on the Google play store is build automatically and then uploaded by GitHub. The version on fdroid is built automatically by fdroid's servers.
But they are totally heard on the exact same source. The difference would be the signature, as fdroid sign the app themselves.

Anyway, glad you are enjoying the app!

**Comment by redwarp** [comment]
My initial privacy policy was this: https://github.com/redwarp/gif-wallpaper/blob/ca6e5100f189380be8b1bed12376e44a8585ab24/docs/privacy.md

But the app got rejected from the store, so I went to a "privacy policy generator" website to make an "official looking one"

**Comment by gbdomubpkm** [comment]
In fact, my questions will enlighten other users I think.

Yes it is a great app.

I'll submit a usability improvement request or two shortly.

Thanks again for your clarification.

**Comment by redwarp** [comment]
I'll update my privacy policy, inspired by this one: https://catima.app/privacy-policy/
The project owner told my that it's what they use, and it was accepted without a hiccup by Google.

**Comment by gbdomubpkm** [comment]
Hello.
It's good you want to update your privacy policy, especially insofar as it can clarify in words what happens concerning the collection or not, the transmission or not of personal data in certain situations (crashes, installation of the apk depending on of such store..).

**Comment by redwarp** [comment]
I published the updated privacy policy, I think it should be more clear and address your concerns ;-)
See https://redwarp.github.io/gif-wallpaper/privacy/

**Comment by gbdomubpkm** [comment]
Thank you very much. It is much more clear and understandable for everyone i think. But did you release the .click ? i don't find 2.0.4 click on github.

**Comment by redwarp** [comment]
I never publish the apk on GitHub.
You must either install from f-droid or the Google Play Store.
F-droid always takes a bit more time to have the update, not sure why.

**Comment by gbdomubpkm** [comment]
Alright, so it's normal not to have found anything. 🙂
First, i thought there was an apk in Assets.

**Comment by gbdomubpkm** [comment]
F-droid 2.0.4 update done
