### ISSUE TITLE
Status bar text color

### ISSUE THREAD

**Issue by PawelAleksandrowicz** [redwarp/gif-wallpaper#266]
Hi,
Love the app, but have a small problem with the color of text in status bar. It's always black, even with black gifs.
![Screenshot_20220909-111333](https://user-images.githubusercontent.com/113173768/189316422-f40d0c7a-585e-42ce-bec1-466ea0d7c908.jpg)

If I go into wallpaper setting, android shows this beige wallpaper color no matter what gif is selected. 
![Screenshot_20220909-111844](https://user-images.githubusercontent.com/113173768/189317107-1b871ca3-0217-4ff0-a86c-e1a8c3196c7c.jpg)
I guess android selects status bar text color based on that and not the actual wallpaper color.

**Comment by redwarp** [comment]
Hey! Not much I can do about that I'm afraid. The live wallpaper is already publishing the colors used by the wallpaper, and then the launcher is supposed to use them accordingly to change the color of status bars and so on.

See https://github.com/redwarp/gif-wallpaper/blob/main/app/src/main/java/net/redwarp/gifwallpaper/GifWallpaperService.kt#L132

If it's not doing that, it is probably a problem with your launcher I'm afraid :-/

**Comment by PawelAleksandrowicz** [comment]
So what do you see in Settings->Wallpapers, where I see this beige preview?
