### ISSUE TITLE
'about' section truncated

### ISSUE THREAD

**Issue by gbdomubpkm** [redwarp/gif-wallpaper#274]
The 'about' section does not display completely: impossible to scroll up in portrait mode (bottom of text truncated), impossible to scroll to the right in landscape mode (text truncated on the left).

![img2](https://user-images.githubusercontent.com/50362604/193476425-d130d1c9-1db6-49b9-bbeb-93704705164b.png)

![img1](https://user-images.githubusercontent.com/50362604/193476477-3f8600a4-29a1-4e81-abc5-9b2338f16ebd.png)

**Comment by redwarp** [comment]
Weird.
What phone are you on, and what version of Android are you using?

**Comment by gbdomubpkm** [comment]
android 11,  smartphone with  6.3 inch screen. This bug is not related to the last update: Already noticed before.

**Comment by gbdomubpkm** [comment]
confirmed fixed.
