### ISSUE TITLE
[Feature]I just want the default brown wallpaper. Can you please tell me how to get this?

### ISSUE THREAD

**Issue by swapneelb** [redwarp/gif-wallpaper#282]
**Is your feature request related to a problem? Please describe.**
No problem at all.

**Describe the solution you'd like**
I just want to the default brown background as my main wallpaper.

**Describe alternatives you've considered**
Tried going through all the files but could not find it.

**Additional context**

![1_launcher](https://user-images.githubusercontent.com/59252456/195923236-099a9a81-6f73-47d9-bdcc-c3366d0244e2.png)

**Comment by redwarp** [comment]
I'm not sure I understand. You want to use the solid colour brown as your wallpaper?

**Comment by swapneelb** [comment]
Yes, that is correct. can you tell me where can i find the wallpaper with the same colour?

**Comment by redwarp** [comment]
I don't know what to tell you. This is a wallpaper you display animated GIFs, not a colour.

If you like the colour and want to use it, is RGB code is val #a57b60

But you will have to find another wallpaper app that lets you choose a fixed colour. I can't help you with that.
