### ISSUE TITLE
Gif execution mode cannot be modified

### ISSUE THREAD

**Issue by gbdomubpkm** [redwarp/gif-wallpaper#284]
Hello.

Thank you again for your app which gives pleasure to watch the smartphone screen 🙂

A small improvement suggested (Maybe you can remove the label 'bug' that I put by mistake, I can't / i don't find how, sorry) : unless i'm mistaken,  It only seems possible to choose the execution mode of a GIF (welcome screen or welcome and lock screen) during the installation of the first GIF. After that, it is not possible to change your choice (unless you completely reset the app)  either for the same Gif or for a new Gif.

I think It would therefore be desirable to include the execution mode of the GIF in the parameters of the app so as to be able to change its choice at any time.

**Comment by redwarp** [comment]
This is actually a system dialog and not something that the app itself does.

So there is sadly nothing that can be done here, that's the way live wallpaper work for some reason.
