### ISSUE TITLE
[Feature] Request: use video and still images instead

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [redwarp/gif-wallpaper#336]
**Is your feature request related to a problem? Please describe.**
Video files are much better in everything compared to animated GIF.
For example how much they take, and how well they are rendered. Also without various restrictions.

**Describe the solution you'd like**
Use video files and image files instead of animated GIF. Maybe offer a conversion step when using GIF as an input.

**Describe alternatives you've considered**
This repository kinda does it:
https://github.com/SCratORS/ImageWallpaperSC

However, it has some issues:
1. Might be a problematic license.
2. Other issues that I've reported : https://github.com/SCratORS/ImageWallpaperSC/issues

**Additional context**

**Comment by redwarp** [comment]
Hey, I don't intend to implement this kind of things, as I intend this app to be simple, focused, to do one thing and one thing only.
Thanks for your interest though.

**Comment by AndroidDeveloperLB** [comment]
@redwarp Don't you agree that MP4 (and video files in general) are superior to GIF ?  Even animated WEBP is usually better.
Instead of direct support of GIF, you could convert it to MP4 and have all of the benefits.
Many websites switched from animated GIF to MP4.

**Comment by redwarp** [comment]
You are totally correct regarding lossless WEBP. MP4, it's debatable: I am using this app to display GIFs made by pixel artists that work with constraint, and choose precisely the color palette they use. MP4 is a lossy format, so it's not as good in my opinion

Another purpose of this project was for me to learn more about gif, how the format works. (I actually implemented the library that decodes the gif format, https://github.com/redwarp/gifdecoder)
I am sharing the source, as I think it's interesting that anybody can take a look at how it works under the hood, and trust that I'm not doing some scammy thing like collecting data or other shit like that ;-)

**Comment by AndroidDeveloperLB** [comment]
@redwarp Actually MP4 can be lossless. 
https://www.movavi.com/learning-portal/avi-vs-mp4.html

I remember someone explained to me that MP4 is just the container, and you choose the codec inside to do the work. 
Maybe I'm not precise about this explanation, but I'm sure that MP4 can be lossless.

Can you please consider making a new one, perhaps? One that supports videos and images?

**Comment by tharubberchicken** [comment]
I love this app and it's simple, yet perfect application of displaying the preciseness of skillfull well-drawn pixel art (for myself at least...) My opinion about adding this extra layer takes away from its original intent and (for me) would almost make it just another run-of-the-mill app. Less is really more and all that. Oh, I have been on the whiskey too...

**Comment by tharubberchicken** [comment]
Well, almost perfect. Once you add my feature request... 😁

**Comment by AndroidDeveloperLB** [comment]
@tharubberchicken It depends on the purpose of the app. If it's to demonstrate a simple thing, better to focus on it alone, than to add more and more features.
It is possible to split a repository into "minimal" and "feature rich", but then it's annoying to maintain both...
When Google presents samples, sadly they often use very complex ones, so it makes it harder for me to learn from them. I personally prefer the simplest sample that there can be. Later I will add my own stuff if I need.
