### ISSUE TITLE
[Feature Request] Gif Shuffling

### ISSUE THREAD

**Issue by Sandvichero** [redwarp/gif-wallpaper#49]
Create collections of gifs which can be shuffled by double tapping or through a configurable timer.

**Comment by redwarp** [comment]
@Sandvichero It's not a bad idea, but do you have an idea about how the UI should look like to allow this kind of feature?
I'm not sure how to not make it to cluttered.

**Comment by Sandvichero** [comment]
> @Sandvichero It's not a bad idea, but do you have an idea about how the UI should look like to allow this kind of feature?
> I'm not sure how to not make it to cluttered.

Here is a mock-up I made of an idea for the UI, underneath the three dot menu there could be a "shuffle" option which would switch the default view to this where you can select a series of Gifs. Once the desired Gifs are selected the use taps next which brings up a box with options such as double tap switch, timer switch length, etc and taps "done"

![Mock Up](https://user-images.githubusercontent.com/26612410/94725642-17ef4a80-032a-11eb-8398-ef4469d8265b.png)

**Comment by redwarp** [comment]
Lost in the sands of time
