### ISSUE TITLE
GIF Wallpaper causes Styles and Wallpapers app to crash on Android 10

### ISSUE THREAD

**Issue by FabianOvrWrt** [redwarp/gif-wallpaper#51]
Using a Moto G7 Power with the official Pixel Experience ROM. Here's a logcat of the crash:
[logcat.txt](https://github.com/redwarp/gif-wallpaper/files/5323904/logcat.txt)

I hope you can fix this, I love to use pixel art (pun not intended) on my home screen.

**Comment by redwarp** [comment]
Hey @FabianOvrWrt , I'm trying to make sense of the log cat and it's hard 😛 
Can you confirm:

- With the app uninstalled, Styles and Wallpapers works fine
- When you reinstall the app, Styles and Wallpapers crashes

I can see the crash you mention in the logcat:

```
10-02 19:53:12.082  4622  4885 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
10-02 19:53:12.082  4622  4885 E AndroidRuntime: Process: com.google.android.apps.wallpaper, PID: 4622
10-02 19:53:12.082  4622  4885 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at com.android.wallpaper.asset.Asset$CenterCropBitmapTask.doInBackground(Asset.java:300)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at com.android.wallpaper.asset.Asset$CenterCropBitmapTask.doInBackground(Asset.java:276)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-02 19:53:12.082  4622  4885 E AndroidRuntime: 	... 4 more
10-02 19:53:12.090  1369  2145 W ActivityTaskManager:   Force finishing activity com.google.android.apps.wallpaper/com.android.customization.picker.CustomizationPickerActivity
```

but I'm not sure it's related to the Gif wallpaper app. 

I found a mention of a similar crash there: https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-lineageos-17-0-oneplus-3-3t-t3990061/page145 and the person with the crash cleared the cache and data of the app "Styles & Wallpapers" and it seemed to help, at last once.

Can you try to do that too, just to see if it helps you? Before I spend more time scratching my head?
Thanks!

**Comment by FabianOvrWrt** [comment]
I've already tried that, but while trying different combinations in my setup I found out two things:

1. GIF Wallpaper will always cause the Style and Wallpapers app to crash **when using a third-party launcher**. These launchers are yet to implement a way in which tapping in the "Wallpaper" option actually goes to the wallpapers page on the Style and Wallpapers app. However, other different live wallpapers I've tested don't have this issue.

2. Using the default launcher works, but **only to change the wallpaper**. Selecting the "Styles and Wallpapers" option in the desktop bubble actually goes to the wallpapers page. However, when using GIF Wallpaper trying to go to the styles page makes the app crash. It will also crash if you try to open it through the display section on the settings app.

To change the UI style, I am currently doing this:
- I select the default launcher and tap on the Styles and Wallpapers option on the desktop.
- I change the wallpaper to a default one.
- I go to Settings > Display > Styles and Wallpapers. The app crashes once, but then the second time it opens normally.
- I change the style and then revert back to GIF Wallpaper.
- I select my custom launcher (Lawnchair 2, but I've tried this with many other launchers).

The Style and Wallpapers app will keep crashing anyway, so it probably is a weird bug born from the combination of all the factors in my setup.

**Comment by redwarp** [comment]
Sorry for the late reply.
So, I've tested Lawnchair 2 as well, and still can't reproduce the crash you get :-/

**Comment by redwarp** [comment]
I can't really test the Pixel Experience rom, as I don't have a phone that I'm willing to flash, sorry...

**Comment by redwarp** [comment]
I have a hunch though: I get some crash with lawnchair, like they are trying to cast some vector drawable to a bitmap drawable.
The Gif Wallpaper thumbnail is indeed a vector drawable, and that could cause issue?
Actually, all the drawables from the app apart from the mipmap icon versions used pre-android 26 are vector drawable.
So it's possible the style and wallpaper struggle with those.
